//
// Created by Maksym Kharchenko on 17.01.2022.
//

#ifndef SIMPLETASKMANAGER_INPUTSHOWTASKLABELSTATE_H
#define SIMPLETASKMANAGER_INPUTSHOWTASKLABELSTATE_H



class InputShowTaskLabelState {

};



#endif //SIMPLETASKMANAGER_INPUTSHOWTASKLABELSTATE_H
