//
// Created by Maksym Kharchenko on 06.12.2021.
//

#ifndef SIMPLETASKMANAGER_TASKACTIONRESULT_H
#define SIMPLETASKMANAGER_TASKACTIONRESULT_H

enum class TaskActionResult {
    SUCCESS,
    FAIL_NO_SUCH_TASK,
    FAIL_CONTROVERSIAL_SUBTASKS
};

#endif //SIMPLETASKMANAGER_TASKACTIONRESULT_H
