//
// Created by Maksym Kharchenko on 06.12.2021.
//

#ifndef SIMPLETASKMANAGER_TASKACTIONRESULT_H
#define SIMPLETASKMANAGER_TASKACTIONRESULT_H

enum class TaskActionResult {
    SUCCESS,
    FAIL_NO_SUCH_TASK,
    FAIL_UNCOMPLETED_SUBTASKS,
    FAIL_NOT_DELETED_SUBTASKS,
    FAIL_INVALID_TASK,
    FAIL_NO_SUCH_LABEL,
    FAIL_SERVER_TROUBLES
};

#endif //SIMPLETASKMANAGER_TASKACTIONRESULT_H
