//
// Created by Maksym Kharchenko on 14.01.2022.
//

#ifndef SIMPLETASKMANAGER_MOCKPERSISTENCEFACTORY_H
#define SIMPLETASKMANAGER_MOCKPERSISTENCEFACTORY_H

#endif //SIMPLETASKMANAGER_MOCKPERSISTENCEFACTORY_H
